<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK2921ad\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK2921ad/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerK2921ad.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerK2921ad\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerK2921ad\appProdProjectContainer([
    'container.build_hash' => 'K2921ad',
    'container.build_id' => 'fae87781',
    'container.build_time' => 1629826452,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK2921ad');
